// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	HI: RequiredParams<'name'>
	PLURAL_FULL: string
	nested: {
		PLURAL: string
	},
	schedule: RequiredParams<'0|simpleDate'>
	spectators: RequiredParams<'0'>
}

export type TranslationFunctions = {
	HI: (arg: { name: string }) => LocalizedString
	PLURAL_FULL: (arg: string | number | boolean) => LocalizedString
	nested: {
		PLURAL: (arg: string | number | boolean) => LocalizedString
	}
	schedule: (arg0: Date) => LocalizedString
	spectators: (arg0: string | number | boolean) => LocalizedString
}

export type Formatters = {}
